site_name: "Fred H. Li"
# site_url: "https://fredhli.github.io"
# site_url: 127.0.0.1:8000
theme:
  name: "material"
  font: 
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: "grey"
      accent: "blue"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "white"
      accent: "blue"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  logo: assets/logos/github-mark-white.png
  favicon: assets/logos/github-mark.svg
  
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    # - navigation.instant.prefetch

nav:
  - Home: index.md
  - Projects: projects.md
  - CV: cv.md
  - Personal: personal.md

markdown_extensions:
  - attr_list

plugins:
  - search
  - tags
  - mkdocs-pdf

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fredhli
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fredhli/
      name: LinkedIn
extra_css:
  - assets/extra.css