site_name: Fred H. Li
site_url: "https://fredhli.github.io"
repo_url: https://github.com/fredhli/fredhli.github.io
repo_name: Repository for this Website
theme:
  name: "material"
  font: 
    text: Open Sans
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: "grey"
      accent: "blue"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "white"
      accent: "blue"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  logo: assets/logos/github-mark-white.png
  favicon: assets/logos/github-mark.svg
  
  features:
    - toc.integrate
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch

nav:
  - Home: index.md
  - Projects: projects.md
  - Sample Codes: sample_codes.md
  - CV: cv.md
  - Cat Collection: personal.md


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences  # 这个扩展可以更好地支持代码块显示

plugins:
  - include-markdown
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-pdf

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fredhli
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fredhli/
      name: LinkedIn



# extra_css:
#   - assets/extra.css