site_name: Fred H. Li
site_url: "https://fredhli.github.io"
repo_url: https://github.com/fredhli/fredhli.github.io
repo_name: Repository for this Website
copyright: Copyright &copy; 2024 Fred Houze Li

theme:
  name: "material"
  font: 
    text: Open Sans
  palette: 
    primary: "white"
    accent: "blue"

  # logo: assets/logos/github-mark-white.png
  logo: assets/logos/github.svg
  favicon: assets/logos/github_file.svg
  
  features:
    - toc.integrate
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.process

nav:
  - Home: index.md
  - Projects: projects.md
  - Research Experience: research_experience.md
  - Sample Codes: sample_codes.md
  - CV: cv.md
  - Personal&nbsp&nbsp: personal.md
  - '<i class="fa-brands fa-linkedin"></i>': https://www.linkedin.com/in/fredhli/
  - '<i class="fa-brands fa-github"></i>': https://www.github.com/fredhli

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: false
      toc_depth: 3
      
plugins:
  - include-markdown
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-pdf
  - mkdocs-jupyter

extra:
  cache_control: no-cache
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fredhli
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fredhli/
      name: LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:<fredhli@outlook.com>


extra_javascript:
  - main.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js

extra_css:
  - css/custom.css